Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -11,7 +11,6 @@ on:
 jobs:
   build:
     runs-on: ubuntu-latest
-
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
@@ -34,24 +33,18 @@ jobs:
         run: |
           cd Teste_API # Entre no diretório onde está o pom.xml
           mvn clean test
-          continue-on-error: true
-          
-      - name: Check Test Logs
-        run: cat Teste_API/target/surefire-reports/*.txt
+        continue-on-error: true # Configurado no nível do passo
+
+      - name: Debug Allure Results Directory
+        run: |
+          cd Teste_API
+          ls -la target || echo "Target directory not found"
+          ls -la target/allure-results || echo "Allure results directory not found"
 
       - name: Generate Allure Report
         run: |
           cd Teste_API
           mvn allure:report
-          
-      - name: Listar arquivos no diretório
-        run: ls -la target/allure-results
-
-      - name: Save Allure Results
-        uses: actions/upload-artifact@v4
-        with:
-          name: allure-results
-          path: target/allure-results
 
 
       - name: Install K6
